name: Dotnet - Build and Format

on:
  push:
      branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Dotnet - Build and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Format
        run: dotnet format --no-restore --verify-no-changes --verbosity diagnostic --severity warn
